apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - consumer-deployment.yaml
  - mq-deployment.yaml
  - mq-service.yaml
  - mynet-networkpolicy.yaml
  - processor-a-deployment.yaml
  - processor-b-deployment.yaml
  - producer-deployment.yaml

commonLabels:
  app.kubernetes.io/name: event-processing
