apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out=./manifests
    kompose.service.port: "5672"
    kompose.service.type: ClusterIP
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mq
  name: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out=./manifests
        kompose.service.port: "5672"
        kompose.service.type: ClusterIP
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mynet: "true"
        io.kompose.service: mq
    spec:
      containers:
        - image: rabbitmq:3-alpine
          name: mq
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}
