apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out=./manifests
    kompose.service.port: "5672"
    kompose.service.type: ClusterIP
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mq
  name: mq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: mq
  type: ClusterIP
status:
  loadBalancer: {}
