apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out=./manifests
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: processor-b
  name: processor-b
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processor-b
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out=./manifests
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mynet: "true"
        io.kompose.service: processor-b
    spec:
      containers:
        - args:
            - /event-processor
            - --consumer-uri
            - amqp://guest:guest@mq:5672
            - --consumer-queue-name
            - hello-for-processor-b
            - --producer-uri
            - amqp://guest:guest@mq:5672
            - --producer-routing-key
            - hello-for-consumer
          image: ghcr.io/vincetse/event-stream:event-processor
          name: processor-b
          resources: {}
      restartPolicy: Always
status: {}
