apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out=./manifests
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out=./manifests
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mynet: "true"
        io.kompose.service: producer
    spec:
      containers:
        - args:
            - /event-producer
            - --uri
            - amqp://guest:guest@mq:5672
            - --routing-key
            - hello-for-processor-a
            - --event-count
            - "999999999"
          image: ghcr.io/vincetse/event-stream:event-processor
          name: producer
          resources: {}
      restartPolicy: Always
status: {}
